version: "3.9"
services:
  backend:
    build: 
        context: ./backend
        dockerfile: Dockerfile
    container_name: "backend"
    command: npm start
    ports: 
        - "801:801"
    volumes:
        - .:/usr/src/app
